ACCESS_TOKEN = 'sl.BWUemw59IPgOxHvwcPbowZ_hI2N0gW8rcKK2KwKdAfOLS7CVNG7Q681YLdcr_YkDhRa5sc2TcKtRvTX2-_BMaD3ub0ECz6o5ah8iI4iwGtlREkTADBEjCbj7NL_nfqpi2uhK1WY-'
FILE_TO_UPLOAD = 'justgray.jpg'
RELATIVE_PATH_TO_FILE = f'resources/{FILE_TO_UPLOAD}'
